### get all products
GET http://localhost:3000/products


### create a product
POST http://localhost:3000/products
Content-Type: application/json

{
    "name":"Apple Watch",
    "price": 499
}


### get a product by id
GET http://localhost:3000/products/6569e570916588a0d789c10d



### update a product by id
PATCH http://localhost:3000/products/6569e570916588a0d789c10d
Content-Type: application/json

{   
    "name": "iMac 2019",
    "price": "799"
}


### delete a product by id
DELETE http://localhost:3000/products/6569decda5949fdf327185d0


### error handler
GET http://localhost:3000/abx_yxz
